#!/bin/sh
INSTALL_PATH='/usr/bin'

if [ `id -u` -ne 0 ]
then
    echo "Need to be ROOT to run install."
    exit 1
fi

if [[ -e 'zruijie' && -e 'runruijie' ]]
then
    install -m 4755 -o root zruijie $INSTALL_PATH
    install -m 0755 -o root runruijie $INSTALL_PATH
else
    echo "Execute files \`zruijie' or \`runruijie' NOT Found."
    echo "Forgot run \`make'?"
    exit 1
fi

echo "####Installation Done.####"

