#!/bin/bash
#用户名
USERNAME=user

#密码
PASSWORD=pass

#其他参数(如--dev指定网卡，可运行zruijie -h查看详细参数)
ARGS=""

#---------------------------------------------------------------------
LOGFILE=/tmp/zruijie.log

echo "Beginning Authentication... "

zruijie -u "$USERNAME" -p "$PASSWORD" --dhcp -b "$@" 2>&1|tee -i "$LOGFILE"
#cat zrj.txt|tee "$LOGFILE"

program_err=`sed -n -e '/^@@ERROR/p' $LOGFILE`
server_info=`sed -n -e '/^>>Server/p' $LOGFILE`
account_info=`sed -n -e '/^>>Account/{N;s/\n//;p}' $LOGFILE`
#rm $LOGFILE
notify(){
    notify-send "锐捷" "$1";
    if [ $? -eq 127 ]; then
        echo "\`notify-send' not installed."
        echo "$1"
    fi
}

for msg in "$program_err" "$server_info" "$account_info"; do
    if [[ $msg ]]; then
        notify "${msg##>>}"
    fi
done


